### PR TITLE
Add function to return stats data for top-<n> mon

### PR DESCRIPTION
**Pull request by jfberry**
As per description and updated README.md:

Sample output showing top 3 ranked Talonflame
```js
ohbem.getPvPRankings(3, 663);
{
  "little": {
    "50": [
      {"rank": 1, "cp": 500, "level": 9, "atk": 0, "def": 14, "sta": 2},
      {"rank": 2, "cp": 500, "level": 8.5, "atk": 5, "def": 15, "sta": 13},
      {"rank": 3, "cp": 500, "level": 9, "atk": 0, "def": 5, "sta": 12}
    ],
    "51": [
      {"rank": 1, "cp": 500, "level": 9, "atk": 0, "def": 14, "sta": 2},
      {"rank": 2, "cp": 500, "level": 8.5, "atk": 5, "def": 15, "sta": 13},
      {"rank": 3, "cp": 500, "level": 9, "atk": 0, "def": 5, "sta": 12}
    ]
  },
  "great": {
    "50": [
      {"rank": 1, "cp": 1496, "level": 26, "atk": 0, "def": 13, "sta": 14},
      {"rank": 1, "cp": 1500, "level": 26, "atk": 0, "def": 13, "sta": 15},
      {"rank": 3, "cp": 1500, "level": 26, "atk": 1, "def": 12, "sta": 14}
    ],
    "51": [
      {"rank": 1, "cp": 1496, "level": 26, "atk": 0, "def": 13, "sta": 14},
      {"rank": 1, "cp": 1500, "level": 26, "atk": 0, "def": 13, "sta": 15},
      {"rank": 3, "cp": 1500, "level": 26, "atk": 1, "def": 12, "sta": 14}
    ]
  },
  "ultra": {
    "50": [
      {"rank": 1, "cp": 2486, "level": 50, "atk": 15, "def": 15, "sta": 14},
      {"rank": 1, "cp": 2493, "level": 50, "atk": 15, "def": 15, "sta": 15},
      {"rank": 3, "cp": 2473, "level": 50, "atk": 14, "def": 15, "sta": 14}
    ],
    "51": [
      {"rank": 1, "cp": 2490, "level": 51, "atk": 13, "def": 15, "sta": 14},
      {"rank": 1, "cp": 2496, "level": 51, "atk": 13, "def": 15, "sta": 15},
      {"rank": 3, "cp": 2495, "level": 51, "atk": 14, "def": 14, "sta": 14}
    ]
  }
}

```

### CODE REVIEW

**Comment by Mygod** [comment]
Wait, so the point is to list top stats for some Pokemon along with its evolutions? (I still do not understand what is the use case for this.)

**Comment by jfberry** [comment]
> Wait, so the point is to list top stats for some Pokemon along with its evolutions? (I still do not understand what is the use case for this.)

The point is to list the stats of the top-n rank of a given pokemon - not sure where evolutions come in (unless I have messed up).

**Comment by Mygod** [comment]
Oh ok I meant to say across all leagues. Still I am not sure why have this combination in particular, instead of:

1. Have query involve evolutions as well.
2. Only query a specific league and a specific level cap.

**Comment by jfberry** [comment]
I just did it across all leagues because that's how obhem works the other way round. I am happy to break out if you think it's more appropriate.
I had considered this a ranking for *this pokemon*, rather than this family of pokemon.  Alternative functions could be written to include evolutions but since IV remains the same you would know what to target anyway?

**Comment by Mygod** [comment]
Okay I will take the PR from here. Thanks!

**Comment by jfberry** [comment]
Thinking about it, in this example above if you asked for top1 you probably should get both tied rank 1 (so two results)

**Comment by Mygod** [comment]
Do you want to include mega evolutions, or keep it separate?

**Comment by Mygod** [comment]
I am taking the liberty to enforce that it shall be separate.

**Comment by Mygod** [comment]
@jfberry Review the new format please.

**Comment by jfberry** [comment]
I think the new format works fine, my choice to separate caps at a higher level was purely arbitrary as the ranks are within the cap.  The same is true now, but you just filter by cap.  This is slightly harder to use and I wonder if you should therefore take the caps array as a parameter? [I would actually call it twice and use the results if this were possible, probably, as code would be more readable]

**Comment by Mygod** [comment]
Why would you want to do that? This format detects level caps automatically. Don't do that.

**Comment by jfberry** [comment]
Perhaps I misunderstand the best way to present the data then, given eg a request to return the top-5 mon - as the rankings will be different depending on the cap chosen?

**Comment by Mygod** [comment]
Take a look at the example in README. 50/51 rankings will be automatically deduplicated via `capped`, and irrelevant leagues/level caps combinations are automatically removed.

**Comment by jfberry** [comment]
Can this be merged?

**Comment by Mygod** [comment]
I'll assume that is an approval then!

**Comment by Mygod** [comment]
Released in v1.4.0.

**Pull request merged**
